language: node_js
node_js:
  - "4.0"
  - "4"
  - "5.0"
  - "5"
  - "6.0"
  - "6"
before_install:
  - "npm install -g npm@latest"
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_script:
    - mysql -u root -e "CREATE DATABASE testQueue;"
    - mysql -u root -e "USE testQueue CREATE TABLE queue (hash CHAR(64), PRIMARY KEY(hash));"
    - mysql -u root -e "USE testQueue ALTER TABLE testQueue ADD COLUMN messageBase64 VARCHAR(120) NOT NULL;"
    - mysql -u root -e "USE testQueue ALTER TABLE testQueue ADD COLUMN requeued BOOLEAN DEFAULT FALSE;"
    - mysql -u root -e "USE testQueue ALTER TABLE testQueue ADD COLUMN heartbeatDeat DATETIME;"
    - mysql -u root -e "USE testQueue ALTER TABLE testQueue ADD COLUMN owner VARCHAR(64);"
    - mysql -u root -e "USE testQueue ALTER TABLE testQueue ADD COLUMN isProcessing BOOLEAN DEFAULT FALSE, INDEX isProcessing(isProcessing);"
    - mysql -u root -e "USE testQueue ALTER TABLE testQueue ADD COLUMN topics VARCHAR(256);"
script:
  # - node bin/manual-testing/polling-heartbeat-test
  # - node bin/manual-testing/wrapped-messages-tests
  - node bin/test-fail
