language: node_js
node_js:
  - "4.0"
  - "4"
  - "5.0"
  - "5"
  - "6.0"
  - "6"
before_install:
  - "npm install -g npm@latest"
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_script:
    - mysql -u root -v -e "CREATE DATABASE testQueue;"
    - mysql -u root -v -D testQueue -e "CREATE TABLE queue (hash CHAR(64), PRIMARY KEY(hash));"
    - mysql -u root -v -D testQueue -e "ALTER TABLE queue ADD COLUMN messageBase64 VARCHAR(120) NOT NULL;"
    - mysql -u root -v -D testQueue -e "ALTER TABLE queue ADD COLUMN requeued BOOLEAN DEFAULT FALSE;"
    - mysql -u root -v -D testQueue -e "ALTER TABLE queue ADD COLUMN heartbeatDeat DATETIME;"
    - mysql -u root -v -D testQueue -e "ALTER TABLE queue ADD COLUMN owner VARCHAR(64);"
    - mysql -u root -v -D testQueue -e "ALTER TABLE queue ADD COLUMN isProcessing BOOLEAN DEFAULT FALSE, INDEX isProcessing(isProcessing);"
    - mysql -u root -v -D testQueue -e "ALTER TABLE queue ADD COLUMN topics VARCHAR(256);"
script:
  - node bin/manual-testing/polling-heartbeat-test
  - node bin/manual-testing/send-message-test
  - node bin/manual-testing/wrapped-message-tests
