language: node_js
node_js:
  - "4.0"
  - "4"
  - "5.0"
  - "5"
  - "6.0"
  - "6"
before_install:
  - "npm install -g npm@latest"
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
script:
    - mysql -u root -v "CREATE DATABASE testQueue;"
    - mysql -u root -v "CREATE USER 'travis'@'localhost' IDENTIFIED BY
      'travis';"
    - mysql -u root -v "GRANT ALL ON testQueue.* TO 'travis'@'localhost';"
    - mysql -u root -v "USE testQueue;"
    - mysql -u root -v "CREATE TABLE queue (hash CHAR(64), PRIMARY
      KEY(hash));"
    - mysql -u root -v "ALTER TABLE testQueue ADD COLUMN messageBase64 VARCHAR(120) NOT NULL;"
    - mysql -u root -v "ALTER TABLE testQueue ADD COLUMN requeued BOOLEAN DEFAULT FALSE;"
    - mysql -u root -v "ALTER TABLE testQueue ADD COLUMN heartbeatDeat DATETIME;"
    - mysql -u root -v "ALTER TABLE testQueue ADD COLUMN owner VARCHAR(120);"
    - mysql -u root -v "ALTER TABLE testQueue ADD COLUMN isProcessing BOOLEAN DEFAULT FALSE, INDEX isProcessing(isProcessing);"
    - mysql -u root -v "ALTER TABLE testQueue ADD COLUMN topics VARCHAR(256);"
